[package]
name = "pyo3_strd"
version = "0.1.0"
authors = ["Federico Marcos <federico.marcos@celerative.com>"]
edition = "2018"

[lib]
name = "pyo3_strd"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]

[dependencies]
levenshtein = "1.0.4"
